/**
 * Mapeo ruta del sidebar → clave de módulo tenant (`tenants.modulos_deshabilitados`).
 */
export const NAV_HREF_MODULE_KEYS: Record<string, string> = {
    '/clinica/pacientes': 'pacientes',
    '/clinica/propietarios': 'propietarios',
    '/clinica/citas': 'citas',
    '/clinica/historias-clinicas': 'historias_clinicas',
    '/clinica/vacunaciones': 'vacunaciones',
    '/clinica/recetas': 'recetas',
    '/clinica/laboratorio': 'laboratorio',
    '/clinica/cirugias': 'cirugias',
    '/clinica/hospitalizacion': 'hospitalizacion',
    '/servicios/grooming': 'grooming',
    '/servicios/hotel': 'hotel',
    '/inventario/productos': 'productos',
    '/inventario/categorias': 'categorias_inventario',
    '/inventario/stock': 'stock',
    '/inventario/movimientos': 'movimientos_stock',
    '/inventario/alertas': 'alertas_stock',
    '/inventario/proveedores': 'proveedores',
    '/inventario/compras': 'compras',
    '/caja/sesiones': 'caja_sesiones',
    '/caja/ventas': 'ventas',
    '/caja/pagos': 'pagos',
    '/caja/descuentos': 'descuentos',
    '/facturacion/documentos': 'documentos',
    '/facturacion/series': 'series',
    '/facturacion/notas-baja': 'notas_baja',
    '/facturacion/resumenes': 'resumenes',
    '/comunicaciones/cola': 'comunicaciones_cola',
    '/comunicaciones/historico': 'comunicaciones_historico',
    '/comunicaciones/bot-ia': 'bot_ia',
    '/comunicaciones/plantillas': 'plantillas',
    '/reportes/snapshots': 'snapshots',
    '/reportes/financiero': 'reporte_financiero',
    '/reportes/top-pacientes': 'reporte_top_pacientes',
    '/configuracion/general': 'config_general',
    '/configuracion/suscripcion': 'config_suscripcion',
    '/configuracion/sedes': 'sedes',
    '/configuracion/roles': 'roles',
    '/configuracion/horarios': 'horarios',
    '/configuracion/bloqueos': 'bloqueos',
    '/configuracion/tarifas': 'tarifas',
    '/configuracion/usuarios': 'usuarios',
    '/auditoria/logs': 'auditoria_logs',
    '/auditoria/login-attempts': 'auditoria_login_attempts',
    '/auditoria/api-logs': 'auditoria_api_logs',
    '/auditoria/tokens': 'auditoria_tokens',
};

export function moduleKeyForHref(href: string): string | undefined {
    return NAV_HREF_MODULE_KEYS[href];
}
