/** Clave de módulo tenant → clave en `nav:items.*` */
export const MODULE_NAV_LABEL_KEYS: Record<string, string> = {
    pacientes: 'pacientes',
    propietarios: 'propietarios',
    citas: 'citas',
    historias_clinicas: 'historias_clinicas',
    vacunaciones: 'vacunaciones',
    recetas: 'recetas',
    laboratorio: 'laboratorio',
    cirugias: 'cirugias',
    hospitalizacion: 'hospitalizacion',
    grooming: 'grooming',
    hotel: 'hotel',
    productos: 'productos',
    categorias_inventario: 'categorias',
    stock: 'stock',
    movimientos_stock: 'movimientos',
    alertas_stock: 'alertas',
    proveedores: 'proveedores',
    compras: 'compras',
    caja_sesiones: 'sesiones',
    ventas: 'ventas',
    pagos: 'pagos',
    descuentos: 'descuentos',
    documentos: 'documentos',
    series: 'series',
    notas_baja: 'notas_baja',
    resumenes: 'resumenes',
    comunicaciones_cola: 'cola_saliente',
    comunicaciones_historico: 'historico',
    bot_ia: 'bot_ia',
    plantillas: 'plantillas',
    snapshots: 'snapshots',
    reporte_financiero: 'financiero',
    reporte_top_pacientes: 'top_pacientes',
    config_general: 'general',
    config_suscripcion: 'suscripcion',
    sedes: 'sedes',
    roles: 'roles',
    horarios: 'horarios',
    bloqueos: 'bloqueos',
    tarifas: 'tarifas',
    usuarios: 'usuarios',
    auditoria_logs: 'logs',
    auditoria_login_attempts: 'login_attempts',
    auditoria_api_logs: 'api_logs',
    auditoria_tokens: 'tokens',
};

export function navLabelKeyForModule(moduleKey: string): string {
    return MODULE_NAV_LABEL_KEYS[moduleKey] ?? moduleKey;
}
