export {
    CAJA_OFFLINE_PATHS,
    CLINICA_OFFLINE_PATHS,
    FACTURACION_OFFLINE_PATHS,
    INVENTARIO_OFFLINE_PATHS,
    SERVICIOS_OFFLINE_PATHS,
    OFFLINE_PATHS,
    isCajaOfflinePath,
    isClinicaOfflinePath,
    isFacturacionOfflinePath,
    isInventarioOfflinePath,
    isServiciosOfflinePath,
    isOfflinePath,
    normalizeOfflinePath,
} from './offline-routes';
